version: '3.8'

services:
  # 1. The Redis Queue
  redis:
    image: redis:alpine
    container_name: pricedelta-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # 2. The PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pricedelta-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pricedelta
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

# 3. Persistent Storage
volumes:
  pgdata: